services:
  mongo:
    image: mongo
    restart: always
    # volumes:
    #   - mongo_data:/data/db
    env_file:
      - .env
  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
      - .env.backend

volumes:
  mongo_data: