services:
  mongo:
    image: mongo
    restart: always
    # volumes:
    #   - mongo_data:/data/db
    env_file:
      - .env
  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
      - .env.backend
  react:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"

volumes:
  mongo_data: